name: twitch
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: ^5.5.4
  google_fonts: ^4.0.4
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.1
  firebase_core: ^2.13.0
  dotted_border: ^2.0.0+2
  image_picker: ^0.8.5+3
  agora_rtc_engine: ^5.3.0
  permission_handler: ^10.0.1
  timeago: ^3.3.0
  http: ^0.13.5
  uuid: ^3.0.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/

