name: twitch
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: ^5.5.4
  google_fonts: ^3.0.1
  firebase_auth: ^3.9.0
  cloud_firestore: ^3.4.8
  firebase_storage: ^10.3.8
  firebase_core: ^1.22.0
  dotted_border: ^2.0.0+2
  image_picker: ^0.8.5+3
  agora_rtc_engine: ^5.3.0
  permission_handler: ^10.0.1
  uuid: ^3.0.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/

