// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcm9Mc-IKXE9x5EcuLp5CxVXGeZl1FJWw',
    appId: '1:295982537426:web:89edf4ee83587aeb522b0b',
    messagingSenderId: '295982537426',
    projectId: 'twitch-a01bd',
    authDomain: 'twitch-a01bd.firebaseapp.com',
    storageBucket: 'twitch-a01bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL5DR6RvINnVVAtOcBTwepSwaLzfvnAB4',
    appId: '1:295982537426:android:9ef5144974812e57522b0b',
    messagingSenderId: '295982537426',
    projectId: 'twitch-a01bd',
    storageBucket: 'twitch-a01bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXQKRmvzRh3If8sdehK0YBufq-4DPpIs8',
    appId: '1:295982537426:ios:2de13461bdc3bcaa522b0b',
    messagingSenderId: '295982537426',
    projectId: 'twitch-a01bd',
    storageBucket: 'twitch-a01bd.appspot.com',
    iosClientId: '295982537426-vi49aouspve6s4tbkt0k8k4s6dugq1ch.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXQKRmvzRh3If8sdehK0YBufq-4DPpIs8',
    appId: '1:295982537426:ios:2de13461bdc3bcaa522b0b',
    messagingSenderId: '295982537426',
    projectId: 'twitch-a01bd',
    storageBucket: 'twitch-a01bd.appspot.com',
    iosClientId: '295982537426-vi49aouspve6s4tbkt0k8k4s6dugq1ch.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitch',
  );
}
